// <auto-generated />
using Bilgisayar_Dal.DataBase.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bilgisayar_Dal.Migrations
{
    [DbContext(typeof(BilgsiyarContext))]
    [Migration("20240912224935_initialBiglisayarSatis")]
    partial class initialBiglisayarSatis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bilgisayar_Dal.DataBase.Models.Anakart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("money")
                        .HasColumnName("decimal");

                    b.HasKey("ID");

                    b.ToTable("Anakarts");
                });

            modelBuilder.Entity("Bilgisayar_Dal.DataBase.Models.Bilgisayar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AnakartId")
                        .HasColumnType("int")
                        .HasColumnName("AnakartID");

                    b.Property<int>("EkranKartıId")
                        .HasColumnType("int")
                        .HasColumnName("EkranKartıID");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IslemciId")
                        .HasColumnType("int")
                        .HasColumnName("IslemciID");

                    b.Property<int>("MarkaId")
                        .HasColumnType("int")
                        .HasColumnName("MarkaID");

                    b.Property<int>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("ModelID");

                    b.Property<int>("RamId")
                        .HasColumnType("int")
                        .HasColumnName("RamID");

                    b.HasKey("ID");

                    b.HasIndex("AnakartId");

                    b.HasIndex("EkranKartıId");

                    b.HasIndex("IslemciId");

                    b.HasIndex("MarkaId");

                    b.HasIndex("ModelId");

                    b.HasIndex("RamId");

                    b.ToTable("Bilgisayars");
                });

            modelBuilder.Entity("Bilgisayar_Dal.DataBase.Models.EkranKartı", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("money")
                        .HasColumnName("decimal");

                    b.HasKey("ID");

                    b.ToTable("EkranKarts");
                });

            modelBuilder.Entity("Bilgisayar_Dal.DataBase.Models.Islemci", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("money")
                        .HasColumnName("decimal");

                    b.HasKey("ID");

                    b.ToTable("Islemcis");
                });

            modelBuilder.Entity("Bilgisayar_Dal.DataBase.Models.Marka", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("money")
                        .HasColumnName("decimal");

                    b.HasKey("ID");

                    b.ToTable("Markas");
                });

            modelBuilder.Entity("Bilgisayar_Dal.DataBase.Models.Model", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("money")
                        .HasColumnName("decimal");

                    b.HasKey("ID");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("Bilgisayar_Dal.DataBase.Models.Ram", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("money")
                        .HasColumnName("decimal");

                    b.HasKey("ID");

                    b.ToTable("Rams");
                });

            modelBuilder.Entity("Bilgisayar_Dal.DataBase.Models.Bilgisayar", b =>
                {
                    b.HasOne("Bilgisayar_Dal.DataBase.Models.Anakart", "Anakart")
                        .WithMany("Bilgisayars")
                        .HasForeignKey("AnakartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bilgisayar_Dal.DataBase.Models.EkranKartı", "EkranKartı")
                        .WithMany("Bilgisayars")
                        .HasForeignKey("EkranKartıId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bilgisayar_Dal.DataBase.Models.Islemci", "Islemci")
                        .WithMany("Bilgisayars")
                        .HasForeignKey("IslemciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bilgisayar_Dal.DataBase.Models.Marka", "Marka")
                        .WithMany("Bilgisayars")
                        .HasForeignKey("MarkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bilgisayar_Dal.DataBase.Models.Model", "Model")
                        .WithMany("Bilgisayars")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bilgisayar_Dal.DataBase.Models.Ram", "Ram")
                        .WithMany("Bilgisayars")
                        .HasForeignKey("RamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anakart");

                    b.Navigation("EkranKartı");

                    b.Navigation("Islemci");

                    b.Navigation("Marka");

                    b.Navigation("Model");

                    b.Navigation("Ram");
                });

            modelBuilder.Entity("Bilgisayar_Dal.DataBase.Models.Anakart", b =>
                {
                    b.Navigation("Bilgisayars");
                });

            modelBuilder.Entity("Bilgisayar_Dal.DataBase.Models.EkranKartı", b =>
                {
                    b.Navigation("Bilgisayars");
                });

            modelBuilder.Entity("Bilgisayar_Dal.DataBase.Models.Islemci", b =>
                {
                    b.Navigation("Bilgisayars");
                });

            modelBuilder.Entity("Bilgisayar_Dal.DataBase.Models.Marka", b =>
                {
                    b.Navigation("Bilgisayars");
                });

            modelBuilder.Entity("Bilgisayar_Dal.DataBase.Models.Model", b =>
                {
                    b.Navigation("Bilgisayars");
                });

            modelBuilder.Entity("Bilgisayar_Dal.DataBase.Models.Ram", b =>
                {
                    b.Navigation("Bilgisayars");
                });
#pragma warning restore 612, 618
        }
    }
}
